### ISSUE TITLE
Add Changes file

### ISSUE THREAD

**Issue by rabbiveesh** [bayashi/Test-Arrow#62]
I've been following the releases of this dist on CPAN. This is cool, but I'd like to know what changed from version to version.
If you add a Changes file, that should show up on CPAN, and make the progress of this dist easier to follow.

**Comment by bayashi** [comment]
hm, I need to change a format to show my Changes up to CPAN.

**Comment by bayashi** [comment]
https://github.com/bayashi/Test-Arrow/pull/64
